---
kind: pipeline
name: python-3-8
type: docker

steps:
- name: test
  image: python:3.8
  commands:
  - apt update
  - apt install --yes graphviz
  - pip install -r requirements.txt
  - pip install .
  - python -m unittest discover tests

# To save energy and resources ci should only run for a few branches
# Related section of the docs: https://docs.drone.io/pipeline/triggers/
trigger:
  branch:
    - main
    - develop
